/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

public class MainTest {
  @Test
  public void testAppExists() {
    Main classUnderTest = new Main();
  }
}
